# Generated by Django 5.1.3 on 2024-11-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_photo_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-time_created',)},
        ),
        migrations.AddField(
            model_name='userfollows',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
