# Generated by Django 5.1.3 on 2024-12-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_ticket_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
