# Generated by Django 5.1.3 on 2024-11-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_super_user',
            new_name='is_superuser',
        ),
    ]
